### ISSUE TITLE
Automatic ssl (ex. let's encrypt) / document with third party like cloudflare

### ISSUE THREAD

**Issue by martinlevesque** [openode-io/openode-api#241]

**Comment by lovasoa** [comment]
### workaround
A workaround for this issue is to use [clouldflare's free HTTPS]( https://www.cloudflare.com/ssl/) proxy. In the "SSL/TLS" tab of the UI, be sure to disable SSL encryption between cloudflare and the final server (on openode). 

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/552629/78269027-546ff400-7509-11ea-8b3b-e0c19b35c7e5.png">

**Comment by martinlevesque** [comment]
Thanks for the feedback. Will more likely document it here https://www.openode.io/docs/platform/ssl.md once we have done more tests.
